#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
$HOME/.config/polybar/launch.sh
xrandr --output HDMI-A-1-0 --primary --set TearFree on --mode 1920x1080 --output DisplayPort-1 --mode 1280x720 --left-of HDMI-A-1-0
bspc monitor HDMI-A-1-0 -d I II III
bspc monitor DisplayPort-1 -d IV V VI
bspc wm -O HDMI-A-1-0 DisplayPort-1

export _JAVA_AWT_WM_NONREPARENTING=1 &
setxkbmap br &
feh --bg-scale ~/Pictures/feh --bg-scale ~/Pictures/wallpapermrrobot.jpg &
vban_receptor -i 192.168.0.8 -p 6980 -s Stream1 -c1 -b pulseaudio &
barrier &
picom &
~/startcantooserver.sh &


bspc config border_width         3
bspc config window_gap          15

bspc config normal_border_color "#bd93f9"
bspc config active_border_color "#bd93f9"
bspc config focused_border_color "#d611b5"
bspc config presel_feedback_color "#bd93f9"



bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
